export class Constants {
  public static BRANDS = [
    { imageUrl: '/assets/brands/Grupo 129.svg' },
    { imageUrl: '/assets/brands/Grupo 130.svg' },
    { imageUrl: '/assets/brands/Grupo 131.svg' },
    { imageUrl: '/assets/brands/Grupo 132.svg' },
    { imageUrl: '/assets/brands/Grupo 133.svg' },
    { imageUrl: '/assets/brands/Grupo 134.svg' },
    { imageUrl: '/assets/brands/Grupo 135.svg' },
    { imageUrl: '/assets/brands/Grupo 136.svg' },
    { imageUrl: '/assets/brands/Grupo 137.svg' },
    { imageUrl: '/assets/brands/Grupo 138.svg' },
    { imageUrl: '/assets/brands/Grupo 140.svg' },
    { imageUrl: '/assets/brands/Grupo 141.svg' },
    { imageUrl: '/assets/brands/Grupo 142.svg' },
    { imageUrl: '/assets/brands/Grupo 143.svg' },
    { imageUrl: '/assets/brands/Grupo 144.svg' },
    { imageUrl: '/assets/brands/Grupo 145.svg' },
    { imageUrl: '/assets/brands/Grupo 146.svg' },
    { imageUrl: '/assets/brands/Grupo 147.svg' },
    { imageUrl: '/assets/brands/Grupo 148.svg' },
    { imageUrl: '/assets/brands/Grupo 149.svg' },
    { imageUrl: '/assets/brands/Grupo 151.svg' },
    { imageUrl: '/assets/brands/Grupo 152.svg' },
    { imageUrl: '/assets/brands/Grupo 153.svg' },
    { imageUrl: '/assets/brands/Grupo 154.svg' },
    { imageUrl: '/assets/brands/Grupo 155.svg' },
    { imageUrl: '/assets/brands/Grupo 156.svg' },
    { imageUrl: '/assets/brands/Grupo 157.svg' },
    { imageUrl: '/assets/brands/Grupo 158.svg' },
    { imageUrl: '/assets/brands/Grupo 161.svg' },
    { imageUrl: '/assets/brands/Grupo 162.svg' },
    { imageUrl: '/assets/brands/Grupo 163.svg' },
    { imageUrl: '/assets/brands/Grupo 164.svg' },
    { imageUrl: '/assets/brands/Grupo 165.svg' },
    { imageUrl: '/assets/brands/Grupo 166.svg' },
    { imageUrl: '/assets/brands/Grupo 167.svg' },
    { imageUrl: '/assets/brands/Grupo 168.svg' },
    { imageUrl: '/assets/brands/Grupo 169.svg' },
    { imageUrl: '/assets/brands/Grupo 170.svg' },
  ];
  public static CARS = [
    { imageUrl: '/assets/cars/van.png', name: 'Van' },
    { imageUrl: '/assets/cars/truck.png', name: 'Truck' },
    { imageUrl: '/assets/cars/sedan.png', name: 'Sedan' },
    { imageUrl: '/assets/cars/exotic.png', name: 'Exotic' },
    { imageUrl: '/assets/cars/hybrid.png', name: 'Hybrid' },
    { imageUrl: '/assets/cars/crossover.png', name: 'Crossover' },
    { imageUrl: '/assets/cars/convertible.png', name: 'Convertible' },
    { imageUrl: '/assets/cars/wagon.png', name: 'Wagon' },
    { imageUrl: '/assets/cars/SUV.png', name: 'Suv' },
    { imageUrl: '/assets/cars/cuope.png', name: 'Cuope' },
    { imageUrl: '/assets/cars/compact.png', name: 'Compact' },
    { imageUrl: '/assets/cars/luxury2.png', name: 'Luxury' },
    { imageUrl: '/assets/cars/motorcycle.png', name: 'Motorcycle' },
  ];
  public static TESTIMONIALS = [
    {
      imageUrl: '/assets/testimonials/1.jpeg',
      name: 'George Marill',
      city: 'Napls - Florida',
      testimonial:
        'Carrleasing.com They did a stellar job finding the perfect vehicle at the right price at exactly the right time. The process was transparent and hassle free from the beginning. I was grateful that there was never a need to step foot inside a dealership. was amazed that the car was dropped off at my house with all the paperwork signed and old lease taken back in less than a half hour. Highly recommend Carrleasing!!',
    },
    {
      imageUrl: '/assets/testimonials/2.jpeg',
      name: 'Charles & Jazmine Johnson',
      city: 'San Jose - California',
      testimonial:
        'These guys are legit and changing the business models for leasing cars. Transaction and info can all be done via your phone. We were fortunate enough to be connected to Daniel who was a great help in guiding us along through the process. We understood that he`s there to help and assist, not take advantage. He cared about us getting the best deal. Thank you Carrleasing!',
    },
    {
      imageUrl: '/assets/testimonials/3.jpeg',
      name: 'Monica & Luis Lopez',
      city: 'San Jose - California',
      testimonial:
        'First time customer here. I always leased before directly from dealers and everyone knows what a pain that IS... well, no more, Carrleasing is here. They delivered exactly on time, and when they said they would. Right on the dot. All papers were ready when the dealer driver arrived and took 30 minutes to sign, then they showed me the car features. right after I got the keys. Documentation stated all amount exactly as what Daniel said it would be... love the car and love the leasing process even more.',
    },
    {
      imageUrl: '/assets/testimonials/4.jpeg',
      name: 'David Salgado',
      city: 'Miami - Florida',
      testimonial:
        'Daniel made me feel like I was his top priority during every interaction we had, unlike past experiences I`ve had before with car salesman. He promptly went over and beyond providing the information on the cars that I was considering to help me find the exact vehicle I was looking for within the budget had, so could make the decision easily from home. The car was even delivered to me at my office.',
    },
  ];
}
