export class Constants {
  public static HOME_CAROUSEL = [
    { imageUrl: '/assets/images/bg/1.png' },
    { imageUrl: '/assets/images/bg/2.png' },
    { imageUrl: '/assets/images/bg/3.png' },
    { imageUrl: '/assets/images/bg/4.png' },
    { imageUrl: '/assets/images/bg/5.png' },
    { imageUrl: '/assets/images/bg/6.png' },
    { imageUrl: '/assets/images/bg/7.png' },
    { imageUrl: '/assets/images/bg/8.png' },
  ];
  public static BRAND_IMAGES = [
    { imageUrl: '/assets/images/brands/Grupo 129.svg' },
    { imageUrl: '/assets/images/brands/Grupo 130.svg' },
    { imageUrl: '/assets/images/brands/Grupo 131.svg' },
    { imageUrl: '/assets/images/brands/Grupo 132.svg' },
    { imageUrl: '/assets/images/brands/Grupo 133.svg' },
    { imageUrl: '/assets/images/brands/Grupo 134.svg' },
    { imageUrl: '/assets/images/brands/Grupo 135.svg' },
    { imageUrl: '/assets/images/brands/Grupo 136.svg' },
    { imageUrl: '/assets/images/brands/Grupo 137.svg' },
    { imageUrl: '/assets/images/brands/Grupo 138.svg' },
    { imageUrl: '/assets/images/brands/Grupo 140.svg' },
    { imageUrl: '/assets/images/brands/Grupo 141.svg' },
    { imageUrl: '/assets/images/brands/Grupo 142.svg' },
    { imageUrl: '/assets/images/brands/Grupo 143.svg' },
    { imageUrl: '/assets/images/brands/Grupo 144.svg' },
    { imageUrl: '/assets/images/brands/Grupo 145.svg' },
    { imageUrl: '/assets/images/brands/Grupo 146.svg' },
    { imageUrl: '/assets/images/brands/Grupo 147.svg' },
    { imageUrl: '/assets/images/brands/Grupo 148.svg' },
    { imageUrl: '/assets/images/brands/Grupo 149.svg' },
    { imageUrl: '/assets/images/brands/Grupo 151.svg' },
    { imageUrl: '/assets/images/brands/Grupo 152.svg' },
    { imageUrl: '/assets/images/brands/Grupo 153.svg' },
    { imageUrl: '/assets/images/brands/Grupo 154.svg' },
    { imageUrl: '/assets/images/brands/Grupo 155.svg' },
    { imageUrl: '/assets/images/brands/Grupo 156.svg' },
    { imageUrl: '/assets/images/brands/Grupo 157.svg' },
    { imageUrl: '/assets/images/brands/Grupo 158.svg' },
    { imageUrl: '/assets/images/brands/Grupo 161.svg' },
    { imageUrl: '/assets/images/brands/Grupo 162.svg' },
    { imageUrl: '/assets/images/brands/Grupo 163.svg' },
    { imageUrl: '/assets/images/brands/Grupo 164.svg' },
    { imageUrl: '/assets/images/brands/Grupo 165.svg' },
    { imageUrl: '/assets/images/brands/Grupo 166.svg' },
    { imageUrl: '/assets/images/brands/Grupo 167.svg' },
    { imageUrl: '/assets/images/brands/Grupo 168.svg' },
    { imageUrl: '/assets/images/brands/Grupo 169.svg' },
    { imageUrl: '/assets/images/brands/Grupo 170.svg' },
  ];
  public static CARS = [
    { imageUrl: '/assets/images/cars/van.png', name: 'Van' },
    { imageUrl: '/assets/images/cars/truck.png', name: 'Truck' },
    { imageUrl: '/assets/images/cars/sedan.png', name: 'Sedan' },
    { imageUrl: '/assets/images/cars/exotic.png', name: 'Exotic' },
    { imageUrl: '/assets/images/cars/hybrid.png', name: 'Hybrid' },
    { imageUrl: '/assets/images/cars/crossover.png', name: 'Crossover' },
    { imageUrl: '/assets/images/cars/convertible.png', name: 'Convertible' },
    { imageUrl: '/assets/images/cars/wagon.png', name: 'Wagon' },
    { imageUrl: '/assets/images/cars/SUV.png', name: 'Suv' },
    { imageUrl: '/assets/images/cars/cuope.png', name: 'Coupe' },
    { imageUrl: '/assets/images/cars/compact.png', name: 'Compact' },
    { imageUrl: '/assets/images/cars/luxury.png', name: 'Luxury' },
    { imageUrl: '/assets/images/cars/motorcycle.png', name: 'Motorcycle' },
  ];
  public static TESTIMONIALS = [
    {
      imageUrl: '/assets/images/testimonials/1.jpeg',
      name: 'George Marill',
      city: 'Naples - Florida',
      testimonial: 'TESTIMONIAL1',
    },
    {
      imageUrl: '/assets/images/testimonials/2.jpeg',
      name: 'Charles & Jazmine Johnson',
      city: 'Chicago - Illinois',
      testimonial: 'TESTIMONIAL2',
    },
    {
      imageUrl: '/assets/images/testimonials/3.jpeg',
      name: 'Monica & Luis Lopez',
      city: 'San José - California',
      testimonial: 'TESTIMONIAL3',
    },
    {
      imageUrl: '/assets/images/testimonials/4.jpeg',
      name: 'David Salgado',
      city: 'Miami - Florida',
      testimonial: 'TESTIMONIAL4',
    },
  ];
  public static STATES = [
    { name: 'Alabama (AL)' },
    { name: 'Alaska (AK)' },
    { name: 'Arizona (AZ)' },
    { name: 'Arkansas (AR)' },
    { name: 'California (CA)' },
    { name: 'Carolina del Norte (NC)' },
    { name: 'Carolina del Sur (SC)' },
    { name: 'Colorado (CO)' },
    { name: 'Connecticut (CT)' },
    { name: 'Dakota del Norte (ND)' },
    { name: 'Dakota del Sur (SD)' },
    { name: 'Delaware (DE)' },
    { name: 'Florida (FL)' },
    { name: 'Georgia (GA)' },
    { name: 'Hawái (HI)' },
    { name: 'Idaho (ID)' },
    { name: 'Illinois (IL)' },
    { name: 'Indiana (IN)' },
    { name: 'Iowa (IA)' },
    { name: 'Kansas (KS)' },
    { name: 'Kentucky (KY)' },
    { name: 'Luisiana (LA)' },
    { name: 'Maine (ME)' },
    { name: 'Maryland (MD)' },
    { name: 'Massachusetts (MA)' },
    { name: 'Míchigan (MI)' },
    { name: 'Minnesota (MN)' },
    { name: 'Misisipi (MS)' },
    { name: 'Misuri (MO)' },
    { name: 'Montana (MT)' },
    { name: 'Nebraska (NE)' },
    { name: 'Nevada (NV)' },
    { name: 'Nueva Jersey (NJ)' },
    { name: 'Nueva York (NY)' },
    { name: 'Nuevo Hampshire (NH)' },
    { name: 'Nuevo México (NM)' },
    { name: 'Ohio (OH)' },
    { name: 'Oklahoma (OK)' },
    { name: 'Oregón (OR)' },
    { name: 'Pensilvania (PA)' },
    { name: 'Rhode Island (RI)' },
    { name: 'Tennessee (TN)' },
    { name: 'Texas (TX)' },
    { name: 'Utah (UT)' },
    { name: 'Vermont (VT)' },
    { name: 'Virginia (VA)' },
    { name: 'Virginia Occidental (WV)' },
    { name: 'Washington (WA)' },
    { name: 'Wisconsin (WI)' },
    { name: 'Wyoming (WY)' },
  ];
  public static BRANDS = [
    { name: 'Buick' },
    { name: 'Cadillac' },
    { name: 'Chevrolet' },
    { name: 'Chrysler' },
    { name: 'Dodge' },
    { name: 'Ferrari' },
    { name: 'Fiat' },
    { name: 'Mercedes Benz' },
    { name: 'Mazda' },
    { name: 'Maserati' },
    { name: 'Lincoln' },
    { name: 'Lexus' },
    { name: 'Lamborghini' },
    { name: 'Land Rover' },
    { name: 'KIA' },
    { name: 'Jeep' },
    { name: 'Jaguar' },
    { name: 'Infiniti' },
    { name: 'Hyundai' },
    { name: 'Honda' },
    { name: 'GMC' },
    { name: 'Ford' },
    { name: 'Mini' },
    { name: 'Mitsubishi' },
    { name: 'Nissan' },
    { name: 'Porsche' },
    { name: 'Subaru' },
    { name: 'Toyota' },
    { name: 'Acura' },
    { name: 'Alfa Romeo' },
    { name: 'Aston Martin' },
    { name: 'Audi' },
    { name: 'BMW' },
    { name: 'Bentley' },
    { name: 'Volkswagen' },
    { name: 'Volvo' },
    { name: 'McLaren' },
    { name: 'Pagani' },
  ];

  public static YEARS = [
    { name: '2000' },
    { name: '2001' },
    { name: '2002' },
    { name: '2003' },
    { name: '2004' },
    { name: '2005' },
    { name: '2006' },
    { name: '2007' },
    { name: '2008' },
    { name: '2009' },
    { name: '2010' },
    { name: '2011' },
    { name: '2012' },
    { name: '2013' },
    { name: '2014' },
    { name: '2015' },
    { name: '2016' },
    { name: '2017' },
    { name: '2018' },
    { name: '2019' },
    { name: '2020' },
  ];

  public static AUDIO_QUALITIES = [{ name: 'Standard' }, { name: 'Premium' }];
  public static BRAKES = [
    { name: 'Disk Brakes' },
    { name: 'Drum Brakes' },
    { name: 'Hydraulic System' },
  ];
  public static TRANSMISSIONS = [
    { name: 'Automatic Transmission' },
    { name: 'Paddle Shift' },
    { name: 'Full Manual' },
  ];
  public static DRIVE_SYSTEMS = [
    { name: '2 Wheel Drive' },
    { name: 'All' },
    { name: '4 Drive System' },
  ];
  public static DURATIONS = [
    { name: '12 months' },
    { name: '24 months' },
    { name: '36 months' },
    { name: '39 months' },
    { name: '48 months' },
    { name: '60 months' },
    { name: '72 months' },
    { name: '84 months' },
    { name: '120 months' },
  ];
}
