export class Constants {
  public static BRANDS = [
    { imageUrl: '/assets/brands/Grupo 129.svg' },
    { imageUrl: '/assets/brands/Grupo 130.svg' },
    { imageUrl: '/assets/brands/Grupo 131.svg' },
    { imageUrl: '/assets/brands/Grupo 132.svg' },
    { imageUrl: '/assets/brands/Grupo 133.svg' },
    { imageUrl: '/assets/brands/Grupo 134.svg' },
    { imageUrl: '/assets/brands/Grupo 135.svg' },
    { imageUrl: '/assets/brands/Grupo 136.svg' },
    { imageUrl: '/assets/brands/Grupo 137.svg' },
    { imageUrl: '/assets/brands/Grupo 138.svg' },
    { imageUrl: '/assets/brands/Grupo 140.svg' },
    { imageUrl: '/assets/brands/Grupo 141.svg' },
    { imageUrl: '/assets/brands/Grupo 142.svg' },
    { imageUrl: '/assets/brands/Grupo 143.svg' },
    { imageUrl: '/assets/brands/Grupo 144.svg' },
    { imageUrl: '/assets/brands/Grupo 145.svg' },
    { imageUrl: '/assets/brands/Grupo 146.svg' },
    { imageUrl: '/assets/brands/Grupo 147.svg' },
    { imageUrl: '/assets/brands/Grupo 148.svg' },
    { imageUrl: '/assets/brands/Grupo 149.svg' },
    { imageUrl: '/assets/brands/Grupo 151.svg' },
    { imageUrl: '/assets/brands/Grupo 152.svg' },
    { imageUrl: '/assets/brands/Grupo 153.svg' },
    { imageUrl: '/assets/brands/Grupo 154.svg' },
    { imageUrl: '/assets/brands/Grupo 155.svg' },
    { imageUrl: '/assets/brands/Grupo 156.svg' },
    { imageUrl: '/assets/brands/Grupo 157.svg' },
    { imageUrl: '/assets/brands/Grupo 158.svg' },
    { imageUrl: '/assets/brands/Grupo 161.svg' },
    { imageUrl: '/assets/brands/Grupo 162.svg' },
    { imageUrl: '/assets/brands/Grupo 163.svg' },
    { imageUrl: '/assets/brands/Grupo 164.svg' },
    { imageUrl: '/assets/brands/Grupo 165.svg' },
    { imageUrl: '/assets/brands/Grupo 166.svg' },
    { imageUrl: '/assets/brands/Grupo 167.svg' },
    { imageUrl: '/assets/brands/Grupo 168.svg' },
    { imageUrl: '/assets/brands/Grupo 169.svg' },
    { imageUrl: '/assets/brands/Grupo 170.svg' },
  ];
  public static CARS = [
    { imageUrl: '/assets/cars/van.png', name: 'Van' },
    { imageUrl: '/assets/cars/truck.png', name: 'Truck' },
    { imageUrl: '/assets/cars/sedan.png', name: 'Sedan' },
    { imageUrl: '/assets/cars/exotic.png', name: 'Exotic' },
    { imageUrl: '/assets/cars/hybrid.png', name: 'Hybrid' },
    { imageUrl: '/assets/cars/crossover.png', name: 'Crossover' },
    { imageUrl: '/assets/cars/convertible.png', name: 'Convertible' },
    { imageUrl: '/assets/cars/wagon.png', name: 'Wagon' },
    { imageUrl: '/assets/cars/SUV.png', name: 'Suv' },
    { imageUrl: '/assets/cars/cuope.png', name: 'Cuope' },
    { imageUrl: '/assets/cars/compact.png', name: 'Compact' },
    { imageUrl: '/assets/cars/luxury2.png', name: 'Luxury' },
    { imageUrl: '/assets/cars/motorcycle.png', name: 'Motorcycle' },
  ];
  public static TESTIMONIALS = [
    {
      imageUrl: '/assets/testimonials/1.jpeg',
      name: 'George Marill',
      city: 'Napls - Florida',
      testimonial:
        'Carrleasing.com hizo un trabajo maravilloso avudandome a encontrar el vehiculo perfecto al precio justo en el momento exacto. El proceso fue muy transparente y sin ningun problema desde el principio. Estoy muy agradecido por el hecho de no haber tenido la necesidad de pisar un concesionario en ningun momento. Me sorprendio mucho que el auto fuera entregado en mi casa con todo el papeleo listo y firmado, ademas de que el contrato de arrendamiento antiguo fue retirado en menos de media hora. Estoy muy agradecido con todo e equipo.',
    },
    {
      imageUrl: '/assets/testimonials/2.jpeg',
      name: 'Charles & Jazmine Johnson',
      city: 'San Jose - California',
      testimonial:
        'Estos chicos son geniales y su propuesta para el arrendamiento de vehiculos es super practica. Recibimos toda la informacion que necesitabamos a tiempo y realizamos toda la transaccion a traves del celular lo que nos permitio ahorrar tiempo y dinero. Tuvimos la suerte de contactar con Daniel, quien fue de gran ayuda para guiarnos a lo largo de todo el proceso. Sentimos que él estaba alli para ayudarnos y no para aprovecharse. El de verdad se preocupo por que obtuviéramos el mejor acuerdo y el mejor vehiculo, justo como lo queriamos. Gracias Carrleasing.com!',
    },
    {
      imageUrl: '/assets/testimonials/3.jpeg',
      name: 'Monica & Luis Lopez',
      city: 'San Jose - California',
      testimonial:
        'Soy un cliente nuevo y es mi primera vez usando esta plataforma. Siempre he arrendado directamente con los distribuidores y siempre ha sido una pesadilla. Bueno, con Carrleasing.com ya no lo fué. Me entregaron el vehiculo a tiempo, cuando y donde dijeron que lo harian. Todos los papeles estaban listos cuando llego el conductor a concesionario y solo tardamos y 30 minutos en firmar los documentos, luego se tomaron el trabajo de mostrarme las caracteristicas y especificaciones del auto. La documentacion fue fiel a los acuerdos previamente establecidos y como se pactaron desde el comienzo. Me encanta mi nuevo auto y me encanta aun mas la practicidad del proceso para obtenerlo.',
    },
    {
      imageUrl: '/assets/testimonials/4.jpeg',
      name: 'David Salgado',
      city: 'Miami - Florida',
      testimonial:
        'Daniel me hizo sentir su prioridad durante todo el proceso y la interaccion que tuvimos, a diferencia de las experiencias pasadas que he tenido con otros intermediarios de autos donde me sentia solo un cliente mas. El fue mas alla de una simple venta y me proporciono toda a informacion necesaria sobre los automoviles que yo estaba considerando elegir para ayudarme • encontrar el vehiculo exacto dentro del presupuesto que tenia disponible. Gracias a su acompañamiento pude sentir la confianza necesaria para poder tomar la decision correcta desde la comodidad de mi casa. Ademas, me entregaron el auto en mi oficina. Gracias por todo Daniel.',
    },
  ];
}
